import React, { useRef, useState, useCallback } from "react";
import { useWallet, useConnection } from "@solana/wallet-adapter-react";
import { useGameState } from "../hooks/useGameState";
import {
  hexGrid,
  hexToPixel,
  hexPath,
  hexKey,
  pixelToHex,
  HEX_SIZE,
} from "../utils/hex";
import {
  getNationPda,
  getTerritoryPda,
  txClaimTerritory,
  getProgram,
} from "../utils/program";
import { PublicKey } from "@solana/web3.js";

// Import IDL — generated by `anchor build`
// TODO: replace with actual IDL after build
// import idl from "../idl/sovereign.json";
const idl: any = null; // placeholder until anchor build runs

const GRID_RADIUS = 7;
const PADDING = 60;

const grid = hexGrid(GRID_RADIUS);

// Compute SVG viewport size
const pixelCoords = grid.map(({ q, r }) => hexToPixel(q, r));
const minX = Math.min(...pixelCoords.map((p) => p.x)) - HEX_SIZE - PADDING;
const maxX = Math.max(...pixelCoords.map((p) => p.x)) + HEX_SIZE + PADDING;
const minY = Math.min(...pixelCoords.map((p) => p.y)) - HEX_SIZE - PADDING;
const maxY = Math.max(...pixelCoords.map((p) => p.y)) + HEX_SIZE + PADDING;
const viewBox = `${minX} ${minY} ${maxX - minX} ${maxY - minY}`;

const WorldMap: React.FC = () => {
  const { publicKey, connected } = useWallet();
  const wallet = useWallet();
  const { connection } = useConnection();
  const { territories, myNation, nations, log, addTerritory } = useGameState();

  const [hoveredHex, setHoveredHex] = useState<string | null>(null);
  const [claiming, setClaiming] = useState<string | null>(null);
  const svgRef = useRef<SVGSVGElement>(null);

  const handleHexClick = useCallback(
    async (q: number, r: number) => {
      if (!connected || !publicKey || !myNation) {
        log("Connect your wallet and found a nation before claiming territory.", "warning");
        return;
      }

      const key = hexKey(q, r);
      if (territories.has(key)) {
        const t = territories.get(key)!;
        log(`Hex (${q},${r}) is already owned by ${t.ownerName}.`, "info");
        return;
      }

      if (!idl) {
        // Demo mode — simulate the claim locally so the map still works
        // without a deployed program
        log(`[DEMO] Claiming territory (${q},${r}) for ${myNation.name}...`, "info");
        setTimeout(() => {
          addTerritory({
            q,
            r,
            ownerPda: myNation.pda,
            ownerColor: myNation.color,
            ownerName: myNation.name,
            militaryPower: 10,
          });
          log(`[DEMO] Territory (${q},${r}) claimed!`, "success");
        }, 800);
        return;
      }

      setClaiming(key);
      try {
        const program = getProgram(connection, wallet, idl);
        const sig = await txClaimTerritory(program, q, r);
        addTerritory({
          q,
          r,
          ownerPda: myNation.pda,
          ownerColor: myNation.color,
          ownerName: myNation.name,
          militaryPower: 10,
        });
        log(`Territory (${q},${r}) claimed by ${myNation.name}!`, "success", sig);
      } catch (err: any) {
        log(`Failed to claim (${q},${r}): ${err.message}`, "error");
      } finally {
        setClaiming(null);
      }
    },
    [connected, publicKey, myNation, territories, connection, wallet, log, addTerritory]
  );

  return (
    <div className="world-map-wrapper">
      <div className="map-legend">
        {nations.map((n) => (
          <div key={n.pda} className="legend-item">
            <span className="legend-dot" style={{ backgroundColor: n.color }} />
            <span>{n.name}</span>
            <span className="legend-power">⚔ {n.militaryPower}</span>
          </div>
        ))}
        {nations.length === 0 && (
          <span className="legend-empty">No nations yet — found yours!</span>
        )}
      </div>

      <svg
        ref={svgRef}
        className="world-map-svg"
        viewBox={viewBox}
        preserveAspectRatio="xMidYMid meet"
      >
        {/* Background */}
        <rect x={minX} y={minY} width={maxX - minX} height={maxY - minY} fill="#0a0f1e" />

        {/* Hex tiles */}
        {grid.map(({ q, r }) => {
          const { x, y } = hexToPixel(q, r);
          const key = hexKey(q, r);
          const territory = territories.get(key);
          const isHovered = hoveredHex === key;
          const isClaiming = claiming === key;
          const isOwned = !!territory;

          const fillColor = isOwned
            ? territory!.ownerColor
            : isHovered
            ? "#1e2d4a"
            : "#111827";

          const strokeColor = isHovered ? "#60a5fa" : isOwned ? "#ffffff22" : "#1e3a5f";
          const strokeWidth = isHovered ? 2 : 1;

          return (
            <g
              key={key}
              onClick={() => handleHexClick(q, r)}
              onMouseEnter={() => setHoveredHex(key)}
              onMouseLeave={() => setHoveredHex(null)}
              style={{ cursor: isOwned ? "default" : "pointer" }}
            >
              <path
                d={hexPath(x, y)}
                fill={fillColor}
                stroke={strokeColor}
                strokeWidth={strokeWidth}
                opacity={isClaiming ? 0.5 : isOwned ? 0.85 : 1}
              />
              {/* Territory coordinates label */}
              <text
                x={x}
                y={y + 4}
                textAnchor="middle"
                fontSize={8}
                fill={isOwned ? "#ffffff88" : "#2d4a6e"}
                pointerEvents="none"
              >
                {q},{r}
              </text>
              {/* Loading spinner effect */}
              {isClaiming && (
                <circle
                  cx={x}
                  cy={y}
                  r={10}
                  fill="none"
                  stroke="#60a5fa"
                  strokeWidth={2}
                  strokeDasharray="30 10"
                >
                  <animateTransform
                    attributeName="transform"
                    type="rotate"
                    from={`0 ${x} ${y}`}
                    to={`360 ${x} ${y}`}
                    dur="1s"
                    repeatCount="indefinite"
                  />
                </circle>
              )}
              {/* Military power badge for owned territories */}
              {isOwned && isHovered && (
                <text
                  x={x}
                  y={y - 14}
                  textAnchor="middle"
                  fontSize={9}
                  fill="#fff"
                  pointerEvents="none"
                >
                  ⚔ {territory!.militaryPower}
                </text>
              )}
            </g>
          );
        })}
      </svg>

      <div className="map-footer">
        <span>
          {territories.size} / {grid.length} territories claimed
        </span>
        {myNation && (
          <span>
            Your nation:{" "}
            <strong style={{ color: myNation.color }}>{myNation.name}</strong>{" "}
            — {Array.from(territories.values()).filter(
              (t) => t.ownerPda === myNation.pda
            ).length}{" "}
            tiles
          </span>
        )}
      </div>
    </div>
  );
};

export default WorldMap;
